/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";
import * as DeltaApi from "../../..";

export class UnexpectedError extends errors.DeltaApiError {
    constructor(body: DeltaApi.Error_) {
        super({
            statusCode: 500,
            body: body,
        });
        Object.setPrototypeOf(this, UnexpectedError.prototype);
    }
}
