/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors";
import * as DeltaApi from "..";

export class NotFoundError extends errors.DeltaApiError {
    constructor(body: DeltaApi.Error_) {
        super({
            statusCode: 404,
            body: body,
        });
        Object.setPrototypeOf(this, NotFoundError.prototype);
    }
}
