/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class DeltaApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, DeltaApiTimeoutError.prototype);
    }
}
