/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class UsedeltaApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, UsedeltaApiTimeoutError.prototype);
    }
}
