/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as DeltaApi from "../../../../api";
import * as core from "../../../../core";

export const JournalEntryCollection: core.serialization.ObjectSchema<
    serializers.JournalEntryCollection.Raw,
    DeltaApi.JournalEntryCollection
> = core.serialization.object({
    accounts: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).JournalEntry)
    ),
});

export declare namespace JournalEntryCollection {
    interface Raw {
        accounts: serializers.JournalEntry.Raw[];
    }
}
