/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as DeltaApi from "../../../../api";
import * as core from "../../../../core";

export const JournalEntryId: core.serialization.Schema<serializers.JournalEntryId.Raw, DeltaApi.JournalEntryId> =
    core.serialization.string();

export declare namespace JournalEntryId {
    type Raw = string;
}
