/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface InventorySet {
    /** Unique identifier of the inventory within delta. */
    id: string;
    /** Unique identifier of the connected platform within delta. */
    connectionId?: string;
    /** The platform-specific ID of the inventory. */
    variantId?: string;
    /** The barcode of the inventory. */
    barcode?: string;
    /** The SKU of the inventory. */
    sku: string;
    /** The total stock of the inventory. */
    totalStock: number;
    /** Automatic time stamp to compare the upt-to-dateness of existing information. */
    changeDate?: string;
    /** Unique identifier of the location within delta. */
    locationId?: string;
    /** The platform-specific ID of the location. */
    locationPlatformId: string;
}
