/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of the account.
 */
export type AccountType =
    | "accounts_payable"
    | "accounts_receivable"
    | "bank"
    | "credit_card"
    | "fixed_asset"
    | "other_asset"
    | "liability"
    | "equity"
    | "expense"
    | "income"
    | "unknown";

export const AccountType = {
    AccountsPayable: "accounts_payable",
    AccountsReceivable: "accounts_receivable",
    Bank: "bank",
    CreditCard: "credit_card",
    FixedAsset: "fixed_asset",
    OtherAsset: "other_asset",
    Liability: "liability",
    Equity: "equity",
    Expense: "expense",
    Income: "income",
    Unknown: "unknown",
} as const;
