/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as UsedeltaApi from "..";

export interface Account {
    id?: UsedeltaApi.AccountId;
    /** Unique identifier of the integration on delta. */
    connectionId?: string;
    /** Unique identifier of platform for the account. */
    accountId: string;
    /** Cateogory of the account. */
    category?: UsedeltaApi.AccountCategory;
    /** Type of the account. */
    type?: UsedeltaApi.AccountType;
    /** Status of the account. */
    status?: UsedeltaApi.AccountStatus;
    /** Nominal code of the account. */
    nominalCode?: string;
    /** Name of the account. */
    name?: string;
    /** Description of the account. */
    description?: string;
    /** Balance of the account. */
    balance?: number;
    /** ISO 4217 currency code associated with the account. */
    currency?: string;
    /** Creation date of the return on the integration platform */
    createdAt?: string;
    /** Last update on the return of the integration platform */
    updatedAt?: string;
}
