/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BillLineItemsItem {
    /** Account number associated with the bill. */
    accountNumber?: string;
    /** Account description associated with the bill. */
    accountDescription?: string;
    /** Article number associated with the bill. */
    articleNumber?: string;
    /** Article description associated with the bill. */
    articleDescription?: string;
    /** Debit associated with the bill. */
    debit?: string;
    /** Debit currency associated with the bill. */
    debitCurrency?: string;
    /** Credit associated with the bill. */
    credit?: string;
    /** Credit currency associated with the bill. */
    creditCurrency?: string;
    /** Project associated with the bill. */
    project?: string;
    /** Transaction information associated with the bill. */
    transactionInformation?: string;
    /** Price associated with the bill. */
    price?: string;
    /** Quantity associated with the bill. */
    quantity?: string;
    /** Total associated with the bill. */
    total?: string;
    /** Unit associated with the bill. */
    unit?: string;
    /** Stock point associated with the bill. */
    stockPoint?: string;
    /** Stock location associated with the bill. */
    stockLocation?: string;
}
