/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BillJournalEntriesItem {
    /** Journal entry id associated to the bill. */
    journalEntryId?: string;
    /** Journal entry series associated to the bill. */
    journalEntrySeries?: string;
    /** Journal Entry year associated to the bill. */
    year?: string;
    /** Journal Entry reference associated to the bill. */
    reference?: string;
}
