/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DeltaApi from "..";

export interface Bill {
    id?: DeltaApi.BillId;
    /** Unique identifier of the integration on delta. */
    connectionId?: string;
    /** Unique identifier of platform for the bill. */
    platformId?: string;
    /** Balance of the bill. */
    balance?: string;
    /** Booked flag for the bill. */
    booked?: boolean;
    /** Cancelled flag for the bill. */
    cancelled?: boolean;
    /** Credit flag for the bill. */
    credit?: boolean;
    /** Currency of the bill. */
    currency?: string;
    /** Currency rate of the bill. */
    currencyRate?: string;
    /** Currency unit of the bill. */
    currencyUnit?: string;
    /** Due date of the bill. */
    dueDate?: string;
    /** External bill number of the bill. */
    externalBillNumber?: string;
    /** External bill series of the bill. */
    externalBillSeries?: string;
    /** Bill date of the bill. */
    billDate?: string;
    /** Supplier number of the bill. */
    supplierNumber?: string;
    /** Supplier name of the bill. */
    supplierName?: string;
    /** A list of journal entries associated with the bill. */
    journalEntries?: DeltaApi.BillJournalEntriesItem[];
    /** Total value of the bill, including taxes. */
    total?: string;
    /** Due date of the bill. */
    duePaymentDate?: string;
    /** A list of line items associated with the bill. */
    lineItems?: DeltaApi.BillLineItemsItem[];
}
