/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DeltaApi from "..";

export interface Customer {
    id?: DeltaApi.CustomerId;
    /** Unique identifier of the integration on delta. */
    connectionId?: string;
    /** Unique identifier of platform for the customer. */
    platformId?: string;
    /** Address of the customer. */
    address1?: string;
    /** Address of the customer. */
    address2?: string;
    /** City of the customer. */
    city?: string;
    /** ISO country code. */
    country?: string;
    /** Email of the customer. */
    email?: string;
    /** Phone number of the customer. */
    phone?: string;
    /** Postal Code of the customer. */
    postalCode?: string;
}
