/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DeltaApi from "..";

export interface Fulfillment {
    /** Unique identifier of the fulfillment within delta. */
    id: string;
    /** The name of the carrier. */
    carrier?: string;
    /** The type of delivery (e.g. Same-Day Delivery, Standard 48h). */
    deliveryType?: string;
    /** The tracking number for the fulfillment. */
    trackingNumber?: string;
    /** The tracking link for the fulfillment.. */
    trackingUrl?: string;
    /** The return tracking number for the fulfillment. Occasionally required to provide by platforms upon fulfillment.. */
    returnTrackingNumber?: string;
    /** The return tracking URL for the fulfillment. Occasionally required to provide by platforms upon fulfillment.. */
    returnTrackingUrl?: string;
    /** The cumulated shipping cost of the order. */
    shipping?: number;
    /** The currency of the shipping cost. (ISO 4217). */
    isoCurrencyCode?: string;
    /** The orders associated with the fulfillment. */
    orders?: DeltaApi.FulfillmentOrdersItem[];
    /** The line_items associated with the fulfillment. */
    lineItems?: DeltaApi.FulfillmentLineItemsItem[];
    /** The number of parcels of the fulfillment. */
    parcels?: number;
    /** The total weight of the parcels in this fulfillment. */
    weight?: number;
    /** The unit of weight of the parcels in this fulfillment. */
    unitWeight?: DeltaApi.FulfillmentUnitWeight;
    /** The date when the order was created. (ISO 8601) */
    createdAt?: string;
    /** The date when the order was last updated. (ISO 8601) */
    updatedAt?: string;
}
