/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The unit of weight of the parcels in this fulfillment.
 */
export type FulfillmentUnitWeight = "kg" | "g" | "lb" | "oz";

export const FulfillmentUnitWeight = {
    Kg: "kg",
    G: "g",
    Lb: "lb",
    Oz: "oz",
} as const;
