/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FulfillmentLineItemsItem {
    /** The platform-specific ID of the line_items. */
    platformId?: string;
    /** The quantity of the line_item. */
    quantity?: string;
}
