/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface InventoryWithoutId {
    id?: string;
    /** Unique identifier of the connected platform within delta. */
    connectionId?: string;
    /** The platform-specific ID of the inventory. */
    variantId?: string;
    /** The barcode of the inventory. */
    barcode?: string;
    /** The SKU of the inventory. */
    sku?: string;
    /** The total stock of the inventory. */
    totalStock?: number;
    /** Unique identifier of the location within delta. */
    locationId?: string;
    /** The platform-specific ID of the location. */
    locationPlatformId?: string;
}
