/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface InvoiceLineItemsItem {
    /** Account number associated with the invoice. */
    accountNumber?: string;
    /** Article number associated with the invoice. */
    articleNumber?: string;
    /** Cost associated with the invoice. */
    cost?: string;
    /** Delivered quantity associated with the invoice. */
    deliveredQuantity?: string;
    /** Description associated with the invoice. */
    description?: string;
    /** Discount associated with the invoice. */
    discount?: string;
    /** Discount type associated with the invoice. */
    discountType?: string;
    /** Price associated with the invoice. */
    price?: string;
    /** Price excluding VAT associated with the invoice. */
    priceExcludingVat?: string;
    /** Total associated with the invoice. */
    total?: string;
    /** Total excluding VAT associated with the invoice. */
    totalExcludingVat?: string;
    /** Unit associated with the invoice. */
    unit?: string;
    /** VAT associated with the invoice. */
    vat?: string;
    /** VAT code associated with the invoice. */
    vatCode?: string;
}
