/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of the location.
 */
export type LocationType = "warehouse" | "store" | "office" | "other";

export const LocationType = {
    Warehouse: "warehouse",
    Store: "store",
    Office: "office",
    Other: "other",
} as const;
