/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the location.
 */
export type LocationStatus = "active" | "inactive" | "unknown";

export const LocationStatus = {
    Active: "active",
    Inactive: "inactive",
    Unknown: "unknown",
} as const;
