/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as UsedeltaApi from "..";

export interface Location {
    /** Unique identifier of the location within delta. */
    id: string;
    /** The platform-specific ID of the location. */
    platformId?: string;
    /** The name of the location. */
    name?: string;
    /** The type of the location. */
    type?: UsedeltaApi.LocationType;
    /** The status of the location. */
    status?: UsedeltaApi.LocationStatus;
    /** The first address line of the address. */
    address1?: string;
    /** The second address line of the address. */
    address2?: string;
    /** The postal code of the address. */
    postalCode?: string;
    /** The city of the address. */
    city?: string;
    /** The region of the address. */
    region?: string;
    /** The country of the address. (ISO 3166-1) */
    countryCode?: string;
}
