/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DeltaApi from "..";

export interface OrderWithoutId {
    id?: number;
    /** Unique identifier of the integration on delta. */
    connectionId?: string;
    /** Name of the connected platform. */
    platform?: string;
    /** Name of the channel on the platform. */
    channel?: string;
    /** The platform-specific ID of the order. */
    platformId?: string;
    /** The channel-specific ID of the order. */
    channelId?: string;
    /** The readable human order id on the connected platform. */
    orderNumber?: string;
    /** Status of the order on the connected platform. */
    status?: DeltaApi.OrderStatus;
    /** Payment status of the order on the connected platform. */
    paymentStatus?: DeltaApi.OrderPaymentStatus;
    /** Fulfillment status of the order on the connected platform, can be one of - NULL None of the line items in the order have been fulfilled. - FULFILLED Every line item in the order has been fulfilled. - PARTIALLY At least one line item in the order has been fulfilled. - RETURNED Every line item in the order has been returned and the order canceled. */
    fulfillmentStatus?: DeltaApi.OrderFulfillmentStatus;
    /** The cumulated discounts applied to the total price. */
    totalOrderDiscount?: number;
    /** The discount codes used in the order. */
    discountCodes?: string;
    /** The total price of the order before taxes. */
    subtotalPrice?: number;
    /** The total price of the order. */
    totalPrice?: number;
    /** The total shipping cost of the order. */
    totalShipping?: number;
    /** The cumulated shipping discounts of the order. */
    totalShippingDiscount?: number;
    /** The total taxes associated with the order. */
    totalTax?: number;
    /** The tax rate for the order. */
    taxRate?: number;
    /** The currency of the order. (ISO 4217). */
    isoCurrencyCode?: string;
    /** The payment method used for the order. */
    paymentMethod?: string;
    /** The number of the invoice associated with the order. */
    invoiceNumber?: string;
    /** The date of the invoice associated with the order. */
    invoiceDate?: string;
    /** Billing address for the order */
    billingAddress?: DeltaApi.OrderBillingAddress;
    /** Billing address for the order */
    shippingAddress?: DeltaApi.OrderShippingAddress;
    /** Items of the order */
    lineItems?: DeltaApi.OrderLineItemsItem[];
    /** The sum of all line item weights. */
    totalWeight?: number;
    /** The unit of the combined line item weights. */
    unitWeight?: string;
    /** Creation date of the order on the integration platform. */
    createdAt?: string;
    /** Updated date of the order in delta. */
    updatedAt?: string;
    /** Fulfillments of the order */
    fulfillments?: DeltaApi.Fulfillment[];
}
