/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface OrderLineItemsItem {
    /** Unique identifier of the line item within delta. */
    id?: number;
    /** The platform-specific ID of the product. */
    platformId?: string;
    /** The platform-specific ID of the variant. Equals platform_id if the product has no variants. */
    variantId?: string;
    /** The barcode for the item. */
    barcode?: string;
    /** The SKU of the item. */
    sku?: string;
    /** The name of the item. */
    name?: string;
    /** The fulfillment status of the order line item on the connected platform. */
    fulfillmentStatus?: string;
    /** The serial number of the item. */
    serialNumber?: string;
    /** Boolean flag whether the item requires shipping. */
    requiresShipping?: boolean;
    /** The weight of the item. */
    weight?: number;
    /** The unit of the weight of the item. */
    unitWeight?: string;
    /** The quantity of sold items of the variant. */
    quantity?: number;
    /** The total discount applied to the sold items of the variant. */
    totalDiscount?: number;
    /** The total price of the sold items of the variant before taxes. */
    subtotalPrice?: number;
    /** The total price of the sold items of the variant. */
    totalPrice?: number;
    /** The tax rate for the line item. */
    taxRate?: number;
    /** The total taxes associated with the line item. */
    totalTax?: number;
    /** The unit cost of the item. */
    unitCost?: number;
    /** The currency of the item. (ISO 4217). */
    isoCurrencyCode?: string;
    /** The delivery time of the item in business days. */
    deliveryTime?: number;
    /** The country of origin of the item. (ISO 3166-1) */
    countryOfOrigin?: string;
    /** Inventory. */
    inventory?: Record<string, unknown>;
    /** Creation date of the line item. */
    createdAt?: string;
    /** Updated date of the line item. */
    updatedAt?: string;
}
