/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The unit type of the item.
 */
export type ProductWithoutIdVariantsItemUnitType = "piece" | "weight";

export const ProductWithoutIdVariantsItemUnitType = {
    Piece: "piece",
    Weight: "weight",
} as const;
