/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Nomenclature of the tariff code
 */
export type ProductWithoutIdVariantsItemCustomsTariffCodesItemNomenclature =
    | "TARIC"
    | "Instrastat"
    | "HS-Code"
    | "Other";

export const ProductWithoutIdVariantsItemCustomsTariffCodesItemNomenclature = {
    Taric: "TARIC",
    Instrastat: "Instrastat",
    HsCode: "HS-Code",
    Other: "Other",
} as const;
