/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The size and weight information of the item..
 */
export interface ProductWithoutIdVariantsItemDimensions {
    /** The width of the item. */
    width?: number;
    /** The height of the item. */
    height?: number;
    /** The length of the item. */
    length?: number;
    /** The unit of the item size. */
    unitSize?: string;
    /** The weight of the item. */
    weight?: number;
    /** The unit of the item weight. */
    unitWeight?: string;
}
