/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as UsedeltaApi from "..";

export interface ProductVariantsItemCustomsTariffCodesItem {
    /** Nomenclature of the tariff code */
    nomenclature?: UsedeltaApi.ProductVariantsItemCustomsTariffCodesItemNomenclature;
    /** ISO Country code associated with the tariff code */
    isoCountryCode?: string;
    /** The tariff code */
    code?: string;
}
