/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DeltaApi from "..";

export interface ProductVariantsItemCustomsTariffCodesItem {
    /** Nomenclature of the tariff code */
    nomenclature?: DeltaApi.ProductVariantsItemCustomsTariffCodesItemNomenclature;
    /** ISO Country code associated with the tariff code */
    isoCountryCode?: string;
    /** The tariff code */
    code?: string;
}
