/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The individual tags or attributes of the item.
 */
export interface ProductWithoutIdVariantsItemTags {
    /** The name of the tag or attribute. */
    name?: string;
    /** The value of the tag or attribute. */
    value?: string;
    /** The language of the tag or attribute. (ISO 639) */
    language?: string;
}
