/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The tax rate of the item.
 */
export type ProductWithoutIdVariantsItemPricingDetailsTaxRate = "reduced" | "normal" | "free";

export const ProductWithoutIdVariantsItemPricingDetailsTaxRate = {
    Reduced: "reduced",
    Normal: "normal",
    Free: "free",
} as const;
