/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Nomenclature of the tariff code
 */
export type ProductVariantsItemCustomsTariffCodesItemNomenclature = "TARIC" | "Instrastat" | "HS-Code" | "Other";

export const ProductVariantsItemCustomsTariffCodesItemNomenclature = {
    Taric: "TARIC",
    Instrastat: "Instrastat",
    HsCode: "HS-Code",
    Other: "Other",
} as const;
