/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as UsedeltaApi from "..";

export interface ProductVariantsItemCustoms {
    /** Array of tariff codes */
    tariffCodes?: UsedeltaApi.ProductVariantsItemCustomsTariffCodesItem[];
}
