/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DeltaApi from "..";

export interface ProductWithoutIdVariantsItemCustoms {
    /** Array of tariff codes */
    tariffCodes?: DeltaApi.ProductWithoutIdVariantsItemCustomsTariffCodesItem[];
}
