/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The media files of the item.
 */
export interface ProductWithoutIdVariantsItemMedia {
    /** The URL of the media file. */
    url?: string;
    /** The type of the media file. */
    type?: string;
}
