/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The condition of the returned items. Can be one of like_new, used, or damaged.
 */
export type ReturnWithoutIdReturnedOrdersItemReturnedItemsItemCondition = "like_new" | "used" | "damaged";

export const ReturnWithoutIdReturnedOrdersItemReturnedItemsItemCondition = {
    LikeNew: "like_new",
    Used: "used",
    Damaged: "damaged",
} as const;
