/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DeltaApi from "..";

export interface ReturnWithoutIdReturnedOrdersItemReturnedItemsItem {
    /** Unique identifier of the line item within delta. */
    id?: number;
    /** vThe platform-specific ID of the product. */
    platformId?: string;
    /** The platform-specific ID of the variant. */
    variantId?: string;
    /** The barcode for the item. */
    barcode?: string;
    /** The SKU of the item. */
    sku?: string;
    /** The number of returned items. */
    quantity?: number;
    /** The reaons of the return. */
    reason?: string;
    /** The condition of the returned items. Can be one of like_new, used, or damaged. */
    condition?: DeltaApi.ReturnWithoutIdReturnedOrdersItemReturnedItemsItemCondition;
}
