/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DeltaApi from "..";

export interface ReturnWithoutIdReturnedOrdersItem {
    /** Unique identifier of the order within delta. */
    id?: number;
    /** The platform-specific ID of the order. */
    platformId?: string;
    /** The list of returned items. */
    returnedItems?: DeltaApi.ReturnWithoutIdReturnedOrdersItemReturnedItemsItem[];
}
