/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as UsedeltaApi from "..";

export interface ReturnReturnedOrdersItem {
    /** Unique identifier of the order within delta. */
    id?: number;
    /** The platform-specific ID of the order. */
    platformId?: string;
    /** The list of returned items. */
    returnedItems?: UsedeltaApi.ReturnReturnedOrdersItemReturnedItemsItem[];
}
