/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * One of sale, refund, or other.
 */
export type TransactionType = "sale" | "refunt" | "other";

export const TransactionType = {
    Sale: "sale",
    Refunt: "refunt",
    Other: "other",
} as const;
