/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetOrdersRequest {
    /**
     * Start date for order filtering in the format YYYY-MM-DD. Orders updated from this date will be returned.
     */
    from?: string;
    /**
     * End date for the orders filtering in the format YYYY-MM-DD. Orders updated before this date will be returned. If not provided, defaults to the current date.
     */
    to?: string;
    /**
     * The next page number for pagination
     */
    next?: number;
    /**
     * The first page number for pagination
     */
    first?: number;
    platformKey?: string;
}
