/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AccountStatus = "active" | "inactive" | "pending";

export const AccountStatus = {
    Active: "active",
    Inactive: "inactive",
    Pending: "pending",
} as const;
