/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DeltaApi from "../../..";

export interface Account {
    id: DeltaApi.AccountId;
    /** Unique identifier of the integration on delta. */
    connectionId: string;
    /** Unique identifier of platform for the account. */
    accountId: string;
    /** Cateogory of the account. */
    category: DeltaApi.AccountCategory;
    /** Type of the account. */
    type: DeltaApi.AccountType;
    /** Status of the account. */
    status: DeltaApi.AccountStatus;
    /** Nominal code of the account. */
    nominalCode: string;
    /** Name of the account. */
    name: string;
    /** Description of the account. */
    description: string;
    /** Balance of the account. */
    balance: number;
    /** ISO 4217 currency code associated with the account. */
    currency: string;
    /** Creation date on the integration platform */
    createdAt: Date;
    /** Last update on the integration platform */
    updatedAt: Date;
}
