/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as DeltaApi from "../../../../api";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<serializers.orders.getOrders.Response.Raw, DeltaApi.Order[]> =
    core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).Order));

export declare namespace Response {
    type Raw = serializers.Order.Raw[];
}
