/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const AccountCategory: core.serialization.Schema<serializers.AccountCategory.Raw, DeltaApi.AccountCategory> =
    core.serialization.enum_(["asset", "expense", "income", "liability", "equity", "unknown"]);

export declare namespace AccountCategory {
    type Raw = "asset" | "expense" | "income" | "liability" | "equity" | "unknown";
}
