/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const AccountCollection: core.serialization.ObjectSchema<
    serializers.AccountCollection.Raw,
    DeltaApi.AccountCollection
> = core.serialization.object({
    orders: core.serialization.list(core.serialization.unknown()).optional(),
});

export declare namespace AccountCollection {
    interface Raw {
        orders?: unknown[] | null;
    }
}
