/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const BillLineItemsItem: core.serialization.ObjectSchema<
    serializers.BillLineItemsItem.Raw,
    DeltaApi.BillLineItemsItem
> = core.serialization.object({
    accountNumber: core.serialization.property("account_number", core.serialization.string().optional()),
    accountDescription: core.serialization.property("account_description", core.serialization.string().optional()),
    articleNumber: core.serialization.property("article_number", core.serialization.string().optional()),
    articleDescription: core.serialization.property("article_description", core.serialization.string().optional()),
    debit: core.serialization.string().optional(),
    debitCurrency: core.serialization.property("debit_currency", core.serialization.string().optional()),
    credit: core.serialization.string().optional(),
    creditCurrency: core.serialization.property("credit_currency", core.serialization.string().optional()),
    project: core.serialization.string().optional(),
    transactionInformation: core.serialization.property(
        "transaction_information",
        core.serialization.string().optional()
    ),
    price: core.serialization.string().optional(),
    quantity: core.serialization.string().optional(),
    total: core.serialization.string().optional(),
    unit: core.serialization.string().optional(),
    stockPoint: core.serialization.property("stock_point", core.serialization.string().optional()),
    stockLocation: core.serialization.property("stock_location", core.serialization.string().optional()),
});

export declare namespace BillLineItemsItem {
    interface Raw {
        account_number?: string | null;
        account_description?: string | null;
        article_number?: string | null;
        article_description?: string | null;
        debit?: string | null;
        debit_currency?: string | null;
        credit?: string | null;
        credit_currency?: string | null;
        project?: string | null;
        transaction_information?: string | null;
        price?: string | null;
        quantity?: string | null;
        total?: string | null;
        unit?: string | null;
        stock_point?: string | null;
        stock_location?: string | null;
    }
}
