/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const BillJournalEntriesItem: core.serialization.ObjectSchema<
    serializers.BillJournalEntriesItem.Raw,
    DeltaApi.BillJournalEntriesItem
> = core.serialization.object({
    journalEntryId: core.serialization.property("journal_entry_id", core.serialization.string().optional()),
    journalEntrySeries: core.serialization.property("journal_entry_series", core.serialization.string().optional()),
    year: core.serialization.string().optional(),
    reference: core.serialization.string().optional(),
});

export declare namespace BillJournalEntriesItem {
    interface Raw {
        journal_entry_id?: string | null;
        journal_entry_series?: string | null;
        year?: string | null;
        reference?: string | null;
    }
}
