/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const BillId: core.serialization.Schema<serializers.BillId.Raw, DeltaApi.BillId> = core.serialization.string();

export declare namespace BillId {
    type Raw = string;
}
