/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const CustomerId: core.serialization.Schema<serializers.CustomerId.Raw, DeltaApi.CustomerId> =
    core.serialization.string();

export declare namespace CustomerId {
    type Raw = string;
}
