/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as UsedeltaApi from "../../api";
import * as core from "../../core";

export const Error_: core.serialization.ObjectSchema<serializers.Error_.Raw, UsedeltaApi.Error_> =
    core.serialization.object({
        message: core.serialization.string(),
    });

export declare namespace Error_ {
    interface Raw {
        message: string;
    }
}
