/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const FulfillmentLineItemsItem: core.serialization.ObjectSchema<
    serializers.FulfillmentLineItemsItem.Raw,
    DeltaApi.FulfillmentLineItemsItem
> = core.serialization.object({
    platformId: core.serialization.property("platform_id", core.serialization.string().optional()),
    quantity: core.serialization.string().optional(),
});

export declare namespace FulfillmentLineItemsItem {
    interface Raw {
        platform_id?: string | null;
        quantity?: string | null;
    }
}
