/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const FulfillmentUnitWeight: core.serialization.Schema<
    serializers.FulfillmentUnitWeight.Raw,
    DeltaApi.FulfillmentUnitWeight
> = core.serialization.enum_(["kg", "g", "lb", "oz"]);

export declare namespace FulfillmentUnitWeight {
    type Raw = "kg" | "g" | "lb" | "oz";
}
