/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as UsedeltaApi from "../../api";
import * as core from "../../core";

export const FulfillmentId: core.serialization.Schema<serializers.FulfillmentId.Raw, UsedeltaApi.FulfillmentId> =
    core.serialization.string();

export declare namespace FulfillmentId {
    type Raw = string;
}
