/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as UsedeltaApi from "../../api";
import * as core from "../../core";

export const Fulfillment: core.serialization.ObjectSchema<serializers.Fulfillment.Raw, UsedeltaApi.Fulfillment> =
    core.serialization.object({
        id: core.serialization.string(),
        carrier: core.serialization.string().optional(),
        deliveryType: core.serialization.property("delivery_type", core.serialization.string().optional()),
        trackingNumber: core.serialization.property("tracking_number", core.serialization.string().optional()),
        trackingUrl: core.serialization.property("tracking_url", core.serialization.string().optional()),
        returnTrackingNumber: core.serialization.property(
            "return_tracking_number",
            core.serialization.string().optional()
        ),
        returnTrackingUrl: core.serialization.property("return_tracking_url", core.serialization.string().optional()),
        shipping: core.serialization.number().optional(),
        isoCurrencyCode: core.serialization.property("iso_currency_code", core.serialization.string().optional()),
        orders: core.serialization
            .list(core.serialization.lazyObject(async () => (await import("..")).FulfillmentOrdersItem))
            .optional(),
        lineItems: core.serialization.property(
            "line_items",
            core.serialization
                .list(core.serialization.lazyObject(async () => (await import("..")).FulfillmentLineItemsItem))
                .optional()
        ),
        parcels: core.serialization.number().optional(),
        weight: core.serialization.number().optional(),
        unitWeight: core.serialization.property(
            "unit_weight",
            core.serialization.lazy(async () => (await import("..")).FulfillmentUnitWeight).optional()
        ),
        createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
        updatedAt: core.serialization.property("updated_at", core.serialization.string().optional()),
    });

export declare namespace Fulfillment {
    interface Raw {
        id: string;
        carrier?: string | null;
        delivery_type?: string | null;
        tracking_number?: string | null;
        tracking_url?: string | null;
        return_tracking_number?: string | null;
        return_tracking_url?: string | null;
        shipping?: number | null;
        iso_currency_code?: string | null;
        orders?: serializers.FulfillmentOrdersItem.Raw[] | null;
        line_items?: serializers.FulfillmentLineItemsItem.Raw[] | null;
        parcels?: number | null;
        weight?: number | null;
        unit_weight?: serializers.FulfillmentUnitWeight.Raw | null;
        created_at?: string | null;
        updated_at?: string | null;
    }
}
