/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const InvoiceLineItemsItem: core.serialization.ObjectSchema<
    serializers.InvoiceLineItemsItem.Raw,
    DeltaApi.InvoiceLineItemsItem
> = core.serialization.object({
    accountNumber: core.serialization.property("account_number", core.serialization.string().optional()),
    articleNumber: core.serialization.property("article_number", core.serialization.string().optional()),
    cost: core.serialization.string().optional(),
    deliveredQuantity: core.serialization.property("delivered_quantity", core.serialization.string().optional()),
    description: core.serialization.string().optional(),
    discount: core.serialization.string().optional(),
    discountType: core.serialization.property("discount_type", core.serialization.string().optional()),
    price: core.serialization.string().optional(),
    priceExcludingVat: core.serialization.property("price_excluding_vat", core.serialization.string().optional()),
    total: core.serialization.string().optional(),
    totalExcludingVat: core.serialization.property("total_excluding_vat", core.serialization.string().optional()),
    unit: core.serialization.string().optional(),
    vat: core.serialization.string().optional(),
    vatCode: core.serialization.property("vat_code", core.serialization.string().optional()),
});

export declare namespace InvoiceLineItemsItem {
    interface Raw {
        account_number?: string | null;
        article_number?: string | null;
        cost?: string | null;
        delivered_quantity?: string | null;
        description?: string | null;
        discount?: string | null;
        discount_type?: string | null;
        price?: string | null;
        price_excluding_vat?: string | null;
        total?: string | null;
        total_excluding_vat?: string | null;
        unit?: string | null;
        vat?: string | null;
        vat_code?: string | null;
    }
}
