/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const InvoiceId: core.serialization.Schema<serializers.InvoiceId.Raw, DeltaApi.InvoiceId> =
    core.serialization.string();

export declare namespace InvoiceId {
    type Raw = string;
}
