/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const JournalEntry: core.serialization.ObjectSchema<serializers.JournalEntry.Raw, DeltaApi.JournalEntry> =
    core.serialization.object({
        id: core.serialization.lazy(async () => (await import("..")).JournalEntryId).optional(),
        connectionId: core.serialization.property("connection_id", core.serialization.string().optional()),
        journalId: core.serialization.property("journal_id", core.serialization.string().optional()),
        description: core.serialization.string().optional(),
        transactionDate: core.serialization.property("transaction_date", core.serialization.string().optional()),
        createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
        updatedAt: core.serialization.property("updated_at", core.serialization.string().optional()),
        currency: core.serialization.string().optional(),
        lineItems: core.serialization.property(
            "line_items",
            core.serialization
                .list(core.serialization.lazyObject(async () => (await import("..")).JournalEntryLineItemsItem))
                .optional()
        ),
    });

export declare namespace JournalEntry {
    interface Raw {
        id?: serializers.JournalEntryId.Raw | null;
        connection_id?: string | null;
        journal_id?: string | null;
        description?: string | null;
        transaction_date?: string | null;
        created_at?: string | null;
        updated_at?: string | null;
        currency?: string | null;
        line_items?: serializers.JournalEntryLineItemsItem.Raw[] | null;
    }
}
