/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const JournalEntryLineItemsItem: core.serialization.ObjectSchema<
    serializers.JournalEntryLineItemsItem.Raw,
    DeltaApi.JournalEntryLineItemsItem
> = core.serialization.object({
    description: core.serialization.string().optional(),
    totalAmount: core.serialization.property("total_amount", core.serialization.number().optional()),
    accountId: core.serialization.property("account_id", core.serialization.string().optional()),
    accountName: core.serialization.property("account_name", core.serialization.string().optional()),
});

export declare namespace JournalEntryLineItemsItem {
    interface Raw {
        description?: string | null;
        total_amount?: number | null;
        account_id?: string | null;
        account_name?: string | null;
    }
}
