/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const LocationId: core.serialization.Schema<serializers.LocationId.Raw, DeltaApi.LocationId> =
    core.serialization.string();

export declare namespace LocationId {
    type Raw = string;
}
