/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const LocationType: core.serialization.Schema<serializers.LocationType.Raw, DeltaApi.LocationType> =
    core.serialization.enum_(["warehouse", "store", "office", "other"]);

export declare namespace LocationType {
    type Raw = "warehouse" | "store" | "office" | "other";
}
