/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const OrderPaymentStatus: core.serialization.Schema<
    serializers.OrderPaymentStatus.Raw,
    DeltaApi.OrderPaymentStatus
> = core.serialization.enum_(["PAYED", "NOT_PAYED", "LOST"]);

export declare namespace OrderPaymentStatus {
    type Raw = "PAYED" | "NOT_PAYED" | "LOST";
}
