/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const OrderId: core.serialization.Schema<serializers.OrderId.Raw, DeltaApi.OrderId> =
    core.serialization.string();

export declare namespace OrderId {
    type Raw = string;
}
