/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const OrderBillingAddress: core.serialization.ObjectSchema<
    serializers.OrderBillingAddress.Raw,
    DeltaApi.OrderBillingAddress
> = core.serialization.object({
    firstName: core.serialization.property("first_name", core.serialization.string().optional()),
    lastName: core.serialization.property("last_name", core.serialization.string().optional()),
    address1: core.serialization.string().optional(),
    address2: core.serialization.string().optional(),
    companyName: core.serialization.property("company_name", core.serialization.string().optional()),
    postalCode: core.serialization.property("postal_code", core.serialization.string().optional()),
    city: core.serialization.string().optional(),
    region: core.serialization.string().optional(),
    countryCode: core.serialization.property("country_code", core.serialization.string().optional()),
    email: core.serialization.string().optional(),
    phone: core.serialization.string().optional(),
    taxType: core.serialization.property("tax_type", core.serialization.string().optional()),
    taxId: core.serialization.property("tax_id", core.serialization.string().optional()),
});

export declare namespace OrderBillingAddress {
    interface Raw {
        first_name?: string | null;
        last_name?: string | null;
        address1?: string | null;
        address2?: string | null;
        company_name?: string | null;
        postal_code?: string | null;
        city?: string | null;
        region?: string | null;
        country_code?: string | null;
        email?: string | null;
        phone?: string | null;
        tax_type?: string | null;
        tax_id?: string | null;
    }
}
