/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as UsedeltaApi from "../../api";
import * as core from "../../core";

export const OrderFulfillmentStatus: core.serialization.Schema<
    serializers.OrderFulfillmentStatus.Raw,
    UsedeltaApi.OrderFulfillmentStatus
> = core.serialization.enum_(["NULL", "FULFILLED", "PARTIALLY", "RETURNED"]);

export declare namespace OrderFulfillmentStatus {
    type Raw = "NULL" | "FULFILLED" | "PARTIALLY" | "RETURNED";
}
