/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const OrderStatus: core.serialization.Schema<serializers.OrderStatus.Raw, DeltaApi.OrderStatus> =
    core.serialization.enum_(["OPEN", "CLOSED", "CANCELLED"]);

export declare namespace OrderStatus {
    type Raw = "OPEN" | "CLOSED" | "CANCELLED";
}
