/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as UsedeltaApi from "../../api";
import * as core from "../../core";

export const ProductVariantsItemCustomsTariffCodesItemNomenclature: core.serialization.Schema<
    serializers.ProductVariantsItemCustomsTariffCodesItemNomenclature.Raw,
    UsedeltaApi.ProductVariantsItemCustomsTariffCodesItemNomenclature
> = core.serialization.enum_(["TARIC", "Instrastat", "HS-Code", "Other"]);

export declare namespace ProductVariantsItemCustomsTariffCodesItemNomenclature {
    type Raw = "TARIC" | "Instrastat" | "HS-Code" | "Other";
}
