/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const ProductVariantsItemTags: core.serialization.ObjectSchema<
    serializers.ProductVariantsItemTags.Raw,
    DeltaApi.ProductVariantsItemTags
> = core.serialization.object({
    name: core.serialization.string().optional(),
    value: core.serialization.string().optional(),
    language: core.serialization.string().optional(),
});

export declare namespace ProductVariantsItemTags {
    interface Raw {
        name?: string | null;
        value?: string | null;
        language?: string | null;
    }
}
