/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const ProductWithoutId: core.serialization.ObjectSchema<
    serializers.ProductWithoutId.Raw,
    DeltaApi.ProductWithoutId
> = core.serialization.lazyObject(async () => (await import("..")).Product);

export declare namespace ProductWithoutId {
    type Raw = serializers.Product.Raw;
}
