/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const ProductWithoutIdVariantsItemCustoms: core.serialization.ObjectSchema<
    serializers.ProductWithoutIdVariantsItemCustoms.Raw,
    DeltaApi.ProductWithoutIdVariantsItemCustoms
> = core.serialization.object({
    tariffCodes: core.serialization.property(
        "tariff_codes",
        core.serialization
            .list(
                core.serialization.lazyObject(
                    async () => (await import("..")).ProductWithoutIdVariantsItemCustomsTariffCodesItem
                )
            )
            .optional()
    ),
});

export declare namespace ProductWithoutIdVariantsItemCustoms {
    interface Raw {
        tariff_codes?: serializers.ProductWithoutIdVariantsItemCustomsTariffCodesItem.Raw[] | null;
    }
}
