/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as UsedeltaApi from "../../api";
import * as core from "../../core";

export const ProductVariantsItemPricingDetailsTaxRate: core.serialization.Schema<
    serializers.ProductVariantsItemPricingDetailsTaxRate.Raw,
    UsedeltaApi.ProductVariantsItemPricingDetailsTaxRate
> = core.serialization.enum_(["reduced", "normal", "free"]);

export declare namespace ProductVariantsItemPricingDetailsTaxRate {
    type Raw = "reduced" | "normal" | "free";
}
