/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as UsedeltaApi from "../../api";
import * as core from "../../core";

export const ProductVariantsItemCustoms: core.serialization.ObjectSchema<
    serializers.ProductVariantsItemCustoms.Raw,
    UsedeltaApi.ProductVariantsItemCustoms
> = core.serialization.object({
    tariffCodes: core.serialization.property(
        "tariff_codes",
        core.serialization
            .list(
                core.serialization.lazyObject(
                    async () => (await import("..")).ProductVariantsItemCustomsTariffCodesItem
                )
            )
            .optional()
    ),
});

export declare namespace ProductVariantsItemCustoms {
    interface Raw {
        tariff_codes?: serializers.ProductVariantsItemCustomsTariffCodesItem.Raw[] | null;
    }
}
