/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const ProductWithoutIdVariantsItemUnitType: core.serialization.Schema<
    serializers.ProductWithoutIdVariantsItemUnitType.Raw,
    DeltaApi.ProductWithoutIdVariantsItemUnitType
> = core.serialization.enum_(["piece", "weight"]);

export declare namespace ProductWithoutIdVariantsItemUnitType {
    type Raw = "piece" | "weight";
}
