/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as UsedeltaApi from "../../api";
import * as core from "../../core";

export const ProductId: core.serialization.Schema<serializers.ProductId.Raw, UsedeltaApi.ProductId> =
    core.serialization.string();

export declare namespace ProductId {
    type Raw = string;
}
