/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const ProductWithoutIdVariantsItemPricingDetails: core.serialization.ObjectSchema<
    serializers.ProductWithoutIdVariantsItemPricingDetails.Raw,
    DeltaApi.ProductWithoutIdVariantsItemPricingDetails
> = core.serialization.object({
    price: core.serialization.number().optional(),
    formerPrice: core.serialization.property("former_price", core.serialization.number().optional()),
    suggestedPrice: core.serialization.property("suggested_price", core.serialization.number().optional()),
    unitCost: core.serialization.property("unit_cost", core.serialization.number().optional()),
    isoCurrencyCode: core.serialization.property("iso_currency_code", core.serialization.string().optional()),
    taxRate: core.serialization.property(
        "tax_rate",
        core.serialization
            .lazy(async () => (await import("..")).ProductWithoutIdVariantsItemPricingDetailsTaxRate)
            .optional()
    ),
});

export declare namespace ProductWithoutIdVariantsItemPricingDetails {
    interface Raw {
        price?: number | null;
        former_price?: number | null;
        suggested_price?: number | null;
        unit_cost?: number | null;
        iso_currency_code?: string | null;
        tax_rate?: serializers.ProductWithoutIdVariantsItemPricingDetailsTaxRate.Raw | null;
    }
}
