/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const ProductWithoutIdVariantsItemCustomsTariffCodesItemNomenclature: core.serialization.Schema<
    serializers.ProductWithoutIdVariantsItemCustomsTariffCodesItemNomenclature.Raw,
    DeltaApi.ProductWithoutIdVariantsItemCustomsTariffCodesItemNomenclature
> = core.serialization.enum_(["TARIC", "Instrastat", "HS-Code", "Other"]);

export declare namespace ProductWithoutIdVariantsItemCustomsTariffCodesItemNomenclature {
    type Raw = "TARIC" | "Instrastat" | "HS-Code" | "Other";
}
