/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const ProductWithoutIdVariantsItemPricingDetailsTaxRate: core.serialization.Schema<
    serializers.ProductWithoutIdVariantsItemPricingDetailsTaxRate.Raw,
    DeltaApi.ProductWithoutIdVariantsItemPricingDetailsTaxRate
> = core.serialization.enum_(["reduced", "normal", "free"]);

export declare namespace ProductWithoutIdVariantsItemPricingDetailsTaxRate {
    type Raw = "reduced" | "normal" | "free";
}
