/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const ReturnStatus: core.serialization.Schema<serializers.ReturnStatus.Raw, DeltaApi.ReturnStatus> =
    core.serialization.enum_(["ANNOUNCED", "TRANSIT", "DELIVERED", "CANCELED", "COMPLETED", "OTHER"]);

export declare namespace ReturnStatus {
    type Raw = "ANNOUNCED" | "TRANSIT" | "DELIVERED" | "CANCELED" | "COMPLETED" | "OTHER";
}
