/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as UsedeltaApi from "../../api";
import * as core from "../../core";

export const ReturnReturnedOrdersItemReturnedItemsItemCondition: core.serialization.Schema<
    serializers.ReturnReturnedOrdersItemReturnedItemsItemCondition.Raw,
    UsedeltaApi.ReturnReturnedOrdersItemReturnedItemsItemCondition
> = core.serialization.enum_(["like_new", "used", "damaged"]);

export declare namespace ReturnReturnedOrdersItemReturnedItemsItemCondition {
    type Raw = "like_new" | "used" | "damaged";
}
