/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const ReturnWithoutIdReturnedOrdersItemReturnedItemsItemCondition: core.serialization.Schema<
    serializers.ReturnWithoutIdReturnedOrdersItemReturnedItemsItemCondition.Raw,
    DeltaApi.ReturnWithoutIdReturnedOrdersItemReturnedItemsItemCondition
> = core.serialization.enum_(["like_new", "used", "damaged"]);

export declare namespace ReturnWithoutIdReturnedOrdersItemReturnedItemsItemCondition {
    type Raw = "like_new" | "used" | "damaged";
}
