/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const ReturnId: core.serialization.Schema<serializers.ReturnId.Raw, DeltaApi.ReturnId> =
    core.serialization.string();

export declare namespace ReturnId {
    type Raw = string;
}
