/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const SupplierId: core.serialization.Schema<serializers.SupplierId.Raw, DeltaApi.SupplierId> =
    core.serialization.string();

export declare namespace SupplierId {
    type Raw = string;
}
