/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as UsedeltaApi from "../../api";
import * as core from "../../core";

export const TransactionPaymentMethod: core.serialization.Schema<
    serializers.TransactionPaymentMethod.Raw,
    UsedeltaApi.TransactionPaymentMethod
> = core.serialization.enum_(["card", "cash", "other"]);

export declare namespace TransactionPaymentMethod {
    type Raw = "card" | "cash" | "other";
}
