/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const TransactionStatus: core.serialization.Schema<
    serializers.TransactionStatus.Raw,
    DeltaApi.TransactionStatus
> = core.serialization.enum_(["success", "failed", "pending", "canceled", "refunded", "other"]);

export declare namespace TransactionStatus {
    type Raw = "success" | "failed" | "pending" | "canceled" | "refunded" | "other";
}
