/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as DeltaApi from "../../api";
import * as core from "../../core";

export const TransactionId: core.serialization.Schema<serializers.TransactionId.Raw, DeltaApi.TransactionId> =
    core.serialization.string();

export declare namespace TransactionId {
    type Raw = string;
}
