/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "./core";
import { Orders } from "./api/resources/orders/client/Client";
import { Products } from "./api/resources/products/client/Client";
import { Inventory } from "./api/resources/inventory/client/Client";
import { Location } from "./api/resources/location/client/Client";
import { Returns } from "./api/resources/returns/client/Client";
import { Transactions } from "./api/resources/transactions/client/Client";
import { Accounts } from "./api/resources/accounts/client/Client";
import { JournalEntries } from "./api/resources/journalEntries/client/Client";
import { Fulfillments } from "./api/resources/fulfillments/client/Client";

export declare namespace DeltaApiClient {
    interface Options {
        environment: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
    }

    interface RequestOptions {
        timeoutInSeconds?: number;
    }
}

export class DeltaApiClient {
    constructor(protected readonly _options: DeltaApiClient.Options) {}

    protected _orders: Orders | undefined;

    public get orders(): Orders {
        return (this._orders ??= new Orders(this._options));
    }

    protected _products: Products | undefined;

    public get products(): Products {
        return (this._products ??= new Products(this._options));
    }

    protected _inventory: Inventory | undefined;

    public get inventory(): Inventory {
        return (this._inventory ??= new Inventory(this._options));
    }

    protected _location: Location | undefined;

    public get location(): Location {
        return (this._location ??= new Location(this._options));
    }

    protected _returns: Returns | undefined;

    public get returns(): Returns {
        return (this._returns ??= new Returns(this._options));
    }

    protected _transactions: Transactions | undefined;

    public get transactions(): Transactions {
        return (this._transactions ??= new Transactions(this._options));
    }

    protected _accounts: Accounts | undefined;

    public get accounts(): Accounts {
        return (this._accounts ??= new Accounts(this._options));
    }

    protected _journalEntries: JournalEntries | undefined;

    public get journalEntries(): JournalEntries {
        return (this._journalEntries ??= new JournalEntries(this._options));
    }

    protected _fulfillments: Fulfillments | undefined;

    public get fulfillments(): Fulfillments {
        return (this._fulfillments ??= new Fulfillments(this._options));
    }
}
