/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const DeltaApiEnvironment = {
    Production: "https://api.usedelta.io/v1",
    Staging: "https://staging.api.usedelta.io/v1",
} as const;

export type DeltaApiEnvironment = typeof DeltaApiEnvironment.Production | typeof DeltaApiEnvironment.Staging;
