/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as DeltaApi from "../../../../api";
import * as core from "../../../../core";

export const AccountCollection: core.serialization.ObjectSchema<
    serializers.AccountCollection.Raw,
    DeltaApi.AccountCollection
> = core.serialization.object({
    accounts: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).Account)),
});

export declare namespace AccountCollection {
    interface Raw {
        accounts: serializers.Account.Raw[];
    }
}
